# create references to Critter IDs in projectroot/.vscode/settings.json
@critter1_attached = 6aea4243-95c6-4174-9061-f797632f530b
@critter2_unattached = eea66d98-1ea0-4fd5-9550-fa056efb2672
### add a new animal
POST http://localhost:3000/upsert-animal?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "animal_id": "test123",
  "animal_status": "ALIVE",
  "juvenile_at_heel": "N",
  "sex": "MALE",
  "wlh_id": "abc123",
  "species": "M-BOBI"
}

### add more than one animal
POST http://localhost:3000/upsert-animal?idir={{idir}} HTTP/1.1
content-type: application/json

[
  {
    "animal_id": "test123",
    "animal_status": "P",
    "juvenile_at_heel": "Y",
    "sex": "M",
    "wlh_id": "abc1233",
    "nickname": "shimmer"
  },
  {
    "animal_id": "test1234",
    "animal_status": "M",
    "juvenile_at_heel": "N",
    "sex": "F",
    "wlh_id": "abc123",
    "nickname": "unknown"
  }
]

### update existing animal
POST http://localhost:3000/upsert-animal?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "critter_id": "{{critter1}}",
  "animal_id": "test123",
  "animal_status": "M",
  "sex": "M",
  "wlh_id": "abc123",
  "nickname": "shimmer"
}

### update multiple animals
POST http://localhost:3000/upsert-animal?idir={{idir}} HTTP/1.1
content-type: application/json

[
  {
    "animal_id": "test123",
    "animal_status": "A",
    "calf_at_heel": true,
    "sex": "M",
    "wlh_id": "abc123",
    "nickname": "shimmer",
    "critter_id": "{{critter1}}"
  },
  {
    "animal_id": "test123",
    "animal_status": "A",
    "sex": "M",
    "wlh_id": "abc123",
    "nickname": "shimmer",
    "critter_id": "{{critter2}}"
  }
]

### get critter history 
http://localhost:3000/get-animal-history/{{critter1}}?idir={{idir}}

### get critters with attached device
http://localhost:3000/get-animals?idir={{idir}}&critterType=assigned

### get critters without device
http://localhost:3000/get-animals?idir={{idir}}&critterType=unassigned

### get unassigned - page 2
http://localhost:3000/get-animals?idir={{idir}}&page=2&critterType=unassigned

### delete individual - fail (no permission)
DELETE http://localhost:3000/animal/{{critter1}}?idir={{idirtest3}} HTTP/1.1

### should succeed
DELETE http://localhost:3000/animal/{{critter1}}?idir={{idir}} HTTP/1.1

### retrieve specific critter
http://localhost:3000/animal/{{critter1_attached}}?idir={{idir}}

### fixme: no current way to fetch specific unattached animal
http://localhost:3000/animal/{{critter2_unattached}}?idir={{idir}}