##### add code header
### should work
POST http://localhost:3000/add-code-header?idir={{idir}} HTTP/1.1
content-type: application/json

{ "code_header_name":"sex", "code_header_title":"Gender" }

### add multiple should work
POST http://localhost:3000/add-code-header?idir={{idir}} HTTP/1.1
content-type: application/json

[
    {"code_header_name":"pop_unit","code_header_title":"population unit"},
    {"code_header_name":"sex","code_header_title":"Gender"}
]

##### add code
###
POST http://localhost:3000/add-code?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "codes": [
    {"code_name": "tokyo", "code_description": "Tokyo, Japan", "code_sort_order": 0, "code_header":"region"}
  ]
}

### code add should fail - header dne
POST http://localhost:3000/add-code?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "codes": [
    {"code_name": "tokyo", "code_description": "Tokyo, Japan", "code_sort_order": 0, "code_header":"regxxion"}
  ]
}

###### get code
GET http://localhost:3000/get-code?codeHeader=region&idir={{idir}} HTTP/1.1

### species 
GET http://localhost:3000/get-code?codeHeader=species&idir={{idir}} HTTP/1.1

###### get code headers
###
GET http://localhost:3000/get-code-headers?idir={{idir}} HTTP/1.1
###
GET http://localhost:3000/get-code-headers?idir={{idir}}&codeType=region HTTP/1.1
