@critter1 = {{existing_critter}}
@attached_to_critter1 = {{collar_attached_to_critter1}}
@critter_no_collar = {{critter_with_change_permission}}
@collar1 = {{existing_collar}}
@collar2 = {{existing_collar2}}
@collarDNE = {{collar_dne}}
@unattached_collar = {{free_collar}}
@today = {{$datetime iso8601}}
### add collar
# this device id already exists - should fail
POST http://localhost:3000/add-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "device_make": "V", "device_model": "deercollar9000", "device_id": 41259
}

###  adding new collars should work
POST http://localhost:3000/add-collar?idir={{idir}} HTTP/1.1
content-type: application/json

[
  {
    "device_id": 99999, "device_make": "T", "device_model": "deercollar9000"
  },
  {
    "device_id": 9998, "device_make": "V", "device_model": "deercollar9000"
  }
]

### update collar
POST http://localhost:3000/update-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "collar_id": "{{collar1}}", "frequency": 291.33, "device_model": "deercollar9000"
}

### update collar that doesn't exist should fail
POST http://localhost:3000/update-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{ "collar_id": "{{collarDNE}}", "frequency": 291.33 }

### retrive collar history
http://localhost:3000/get-collar-history/{{collar1}}?idir={{idir}}

##### collar assignment tests
# should fail - already attached in dev
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": true,
  "data": {
    "collar_id": "{{collar1}}",
    "animal_id": "{{critter1}}",
    "valid_from": "{{today}}"
  }
}

### should work
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": true,
  "data": {
    "collar_id": "{{free_collar}}",
    "animal_id": "{{critter_no_collar}}",
    "valid_from": "{{today}}"
  }
}

### unlinking collar
# should succeed
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": false,
  "data": {
    "collar_id": "{{attached_to_critter1}}",
    "animal_id": "{{critter1}}",
    "valid_from": "{{today}}"
  }
}

### collar queries
# get available collars
http://localhost:3000/get-available-collars?idir={{idir}}

### get paged available collars
http://localhost:3000/get-available-collars?idir={{idir}}&page=2

### get assigned collars
http://localhost:3000/get-assigned-collars?idir={{idir}}

### get assigned collars page 2
http://localhost:3000/get-assigned-collars?idir={{idir}}&page=2

### - should pass
DELETE http://localhost:3000/collar/{{existing_collar2}}?idir={{idir}} HTTP/1.1