##### add collar
##### 
# this device id already exists - should fail
POST http://localhost:3000/add-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "collar_make": "vectronics",
  "collar_model": "deercollar9000",
  "device_id": 41259
}

###  adding a new collar should work
POST http://localhost:3000/add-collar?idir={{idir}} HTTP/1.1
content-type: application/json

[
  {
    "device_id": 99999,
    "collar_make": "vectronics",
    "collar_model": "deercollar9000"
  },
  {
    "device_id": 9998,
    "collar_make": "vectronics",
    "collar_model": "deercollar9000"
  }
]

### update collar
POST http://localhost:3000/update-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "collar_id": "5055375f-f91a-4cd7-aa4f-e0dbef56a358",
  "radio_frequency": 291.33
}

###
http://localhost:3000/get-collar-history/5055375f-f91a-4cd7-aa4f-e0dbef56a358?idir={{idir}}

##### linking collar to animal
# should fail - animal asigned
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": true,
  "data": {
    "device_id": 21511,
    "animal_id": 3,
    "valid_from": "2021-10-20"
  }
}

### should work
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": true,
  "data": {
    "device_id": 41260,
    "animal_id": 100,
    "valid_from": "2021-10-20"
  }
}

##### unlinking collar
##### 
### should fail because 21511 is assigned to TWC1009
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": false,
  "data": {
    "collar_id": 148,
    "animal_id": 4
  }
}

### should work, will end assignment today because endDate is not provided
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": false,
  "data": {
    "collar_id": 148,
    "animal_id": 70
  }
}

### should work
POST http://localhost:3000/change-animal-collar?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "isLink": false,
  "data": {
    "collar_id": 148,
    "animal_id": 70, 
    "valid_from": "2021-12-01"
  }
}

######
### get available collars
http://localhost:3000/get-available-collars?idir={{idir}}

### get paged available collars
http://localhost:3000/get-available-collars?idir={{idir}}&page=2

### specific collar
http://localhost:3000/get-available-collars?idir={{idir}}&id=a84cf03c-225c-4984-930b-1f259c9926c8

### get assigned collars
http://localhost:3000/get-assigned-collars?idir={{idir}}

### get assigned collars page 2
http://localhost:3000/get-assigned-collars?idir={{idir}}&page=2

### get one collar
# http://localhost:3000/collar/37876?idir={{idir}}