### get multiple critter history data 
POST http://localhost:3000/export/animal/?idir={{idir}}
content-type: application/json

[
"{{existing_critter}}",
"{{existing_critter2}}"
]

### get collar history data
POST http://localhost:3000/export/collar?idir={{idir}}&id={{collar_attached_to_critter1}}
content-type: application/json

[
    "{{collar_attached_to_critter1}}"
]

### get 2 collar history data
POST http://localhost:3000/export/collar?idir={{idir}}
content-type: application/json

[
    "{{collar_attached_to_critter1}}",
    "{{existing_critter2}}"
]

### get movement history
POST http://localhost:3000/export/movement?idir={{idir}}&id={{existing_critter2}} HTTP/1.1
content-type: application/json

[
    "{{existing_critter}}"
]

### get movement history x2
POST http://localhost:3000/export/movement?idir={{idir}} HTTP/1.1
content-type: application/json

[
    "{{existing_critter}}",
    "{{existing_critter2}}"
]