@badrole = adminstrato
@badaccess = notpending
@validrole = user
@validaccess = pending
@granted = granted
@denied = denied

# note: pending_request_id is set in .vscode/settings.json

### fail - missing username field
POST http://localhost:3000/submit-onboarding-request?idir=hithere HTTP/1.1
content-type: application/json

{
	"domain": "idir",
	"access": "{{validaccess}}",
	"lastname": "test",
	"firstname": "bill",
	"phone": "321-123-1232",
	"email": "test@mail.com",
	"role_type": "{{validrole}}"
}

### fail - invalid role
POST http://localhost:3000/submit-onboarding-request?idir=hithere HTTP/1.1
content-type: application/json

{
	"domain": "idir",
	"access": "{{validaccess}}",
	"lastname": "test",
	"firstname": "bill",
	"phone": "321-123-1232",
	"email": "test@mail.com",
	"role_type": "{{badrole}}",
	"username": "hithere"
}

### fail - invalid access
POST http://localhost:3000/submit-onboarding-request?idir=hithere HTTP/1.1
content-type: application/json

{
	"domain": "idir",
	"access": "{{badaccess}}",
	"lastname": "test",
	"firstname": "bill",
	"phone": "321-123-1232",
	"email": "test@mail.com",
	"role_type": "{{validrole}}",
	"username": "hithere"
}

### should fail - this request exists
POST http://localhost:3000/submit-onboarding-request?idir=hithere HTTP/1.1
content-type: application/json

{
	"domain": "bceid",
	"access": "{{validaccess}}",
	"lastname": "test",
	"firstname": "bill",
	"phone": "321-123-1232",
	"email": "test@mail.com",
	"role_type": "{{validrole}}",
	"username": "{{onboard_username_exists}}"
}

### should succeed 
POST http://localhost:3000/submit-onboarding-request?idir=imanewguy HTTP/1.1
content-type: application/json

{
	"domain": "idir",
	"access": "{{validaccess}}",
	"lastname": "test",
	"firstname": "bill",
	"phone": "321-123-1232",
	"email": "test@mail.com",
	"role_type": "{{validrole}}",
	"username": "imanewguy"
}

### although this request exists, this should succeed 
### as the request is in denied state.
POST http://localhost:3000/submit-onboarding-request?idir=imanewguy HTTP/1.1
content-type: application/json

{
	"domain": "bceid",
	"access": "{{validaccess}}",
	"phone": "321-123-1232",
	"email": "test@mail.com",
	"role_type": "{{validrole}}",
	"username": "{{onboard_username_exists_but_denied}}"
}

### retrieve existing requests
http://localhost:3000/onboarding-requests?idir={{idir}}

### should fail with unauthorized
POST http://localhost:3000/handle-onboarding-request?idir=imanewguy HTTP/1.1
content-type: application/json

{
	"domain": "idir"
}

### onboarding request admin handling a submission

### should fail - id DNE
POST http://localhost:3000/handle-onboarding-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
	"onboarding_id": 99,
	"access": "granted",
	"role_type": "observer"
}

### should fail - invalid access type
POST http://localhost:3000/handle-onboarding-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
	"onboarding_id": "{{pending_request_id}}",
	"access": "{{badaccess}}",
	"role_type": "observer"
}

### should fail - invalid access type
POST http://localhost:3000/handle-onboarding-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
	"onboarding_id": "{{pending_request_id}}",
	"access": "{{granted}}",
	"role_type": "{{badrole}}"
}
### should succeed with value false (denied)
POST http://localhost:3000/handle-onboarding-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
	"onboarding_id": "{{pending_request_id}}",
	"access": "{{denied}}",
	"role_type":  "{{validrole}}"
}
### should suceed with true (granted)
POST http://localhost:3000/handle-onboarding-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
	"onboarding_id": "{{pending_request_id}}",
	"access": "{{granted}}",
	"role_type": "{{validrole}}",
	"email": "{{email}}",
	"firstname": "{{firstname}}"
}

# onboard status test

### fail: no status 
http://localhost:3000/get-onboard-status?idir={{idir}}

###
http://localhost:3000/get-onboard-status?bceid=hithere

### should be denied
http://localhost:3000/get-onboard-status?bceid=kmb_bctw_observer3