@critter1 = {{existing_critter}}
@critter2 = {{existing_critter2}}
# invalid because no bctw.users are using it
@invalid_email = test1@g.com
@valid_email = {{email_valid}}
@valid_email2 = {{email_valid2}}

@request_id_valid = 6
@request_id_invalid = 7

### submit a request - should fail as one of the email addresses DNE
POST http://localhost:3000/submit-permission-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user_email_list": ["{{invalid_email}}", "{{valid_email}}"],
  "critter_permissions_list": [
    {"animal_id" : "{{critter1}}", "permission_type": "view"},
    {"animal_id" : "{{critter2}}", "permission_type": "subowner"}
  ]
}

### submit a request - should fail, 2nd object in critter_permission_list is malformed
POST http://localhost:3000/submit-permission-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user_email_list": ["{{valid_email}}"],
  "critter_permissions_list": [
    {"animal_id" : "{{critter1}}", "permission_type": "view"},
    {"animl_id" : "{{critter2}}", "permission_type": "subowner"}
  ]
}

### submit a request - succeed
POST http://localhost:3000/submit-permission-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user_email_list": ["{{valid_email}}"],
  "critter_permissions_list": [
    {"animal_id" : "{{critter1}}", "permission_type": "view"},
    {"animal_id" : "{{critter2}}", "permission_type": "subowner"}
  ]
}

### get existing requests
GET http://localhost:3000/permission-request?idir={{idir}} HTTP/1.1

### handle a request 
POST http://localhost:3000/execute-permission-request?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "request_id": "{{request_id_valid}}",
  "is_grant": true
}
