http://localhost:3000/get-last-pings

###

http://localhost:3000/get-critters

###

http://localhost:3000/

###

http://localhost:3000/role?idir=stuff

###

http://localhost:3000/role?idir=jcraven

###

http://localhost:3000/user-collars?idir=jcraven
