http://localhost:3000/get-last-pings

###

http://localhost:3000/get-critters?idir=jcraven

###

http://localhost:3000/

###

http://localhost:3000/role

###

http://localhost:3000/role?idir=stuff

###

http://localhost:3000/role?idir=jcraven

###

http://localhost:3000/user-collars?idir=jcraven

###

POST http://localhost:3000/grant-collars?idir=jcraven HTTP/1.1
content-type: application/json

{
  "grantToIdir": "jrpopkin",
  "accessType": "view",
  "collarIds":[101583, 101775, 101827]
}

### 

# should fail, no collar ids supplied
POST http://localhost:3000/grant-collars?idir=jcraven HTTP/1.1
content-type: application/json

{
  "idir": 
  "accessType": "view",
  "collarIds":[]
}

###
POST http://localhost:3000/add-user HTTP/1.1
content-type: application/json

{
  "user": {
    "idir": "vchongvv",
    "email": "vchong@qt.com"
  },
  "role": "administrator"
}

###

POST http://localhost:3000/add-user HTTP/1.1
content-type: application/json

{
  "user": {
    "idir": "vchongv",
    "email": "vchong@qt.com"
  },
  "role": "administrat"
}