http://localhost:3000/role

###
http://localhost:3000/role?idir=stuff

###
http://localhost:3000/role?idir={{idir}}

###
POST http://localhost:3000/add-user HTTP/1.1
content-type: application/json

{
  "user": {
    "idir": "someguy",
    "email": "someguy@qt.com"
  },
  "role": "administrator"
}

###
POST http://localhost:3000/add-user HTTP/1.1
content-type: application/json

{
  "user": {
    "idir": "someguy",
    "email": "someguy@qt.com"
  },
  "role": "administrat"
}