http://localhost:3000/role

###
http://localhost:3000/role?idir=stuff

###
http://localhost:3000/role?idir={{idir}}

###
POST http://localhost:3000/add-user HTTP/1.1
content-type: application/json

{
  "user": {
    "idir": "someguy",
    "email": "someguy@qt.com"
  },
  "role": "administrator"
}

### should fail invalid role type
POST http://localhost:3000/add-user HTTP/1.1
content-type: application/json

{
  "user": {
    "idir": "someguy",
    "email": "someguy@qt.com"
  },
  "role": "administrat"
}

###
# should fail, user with this idir already has access to this critter
POST http://localhost:3000/assign-critter-to-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "animalId": 3,
  "start": "2020-12-01",
  "end": "2021-12-01"
}

### - should succeed with my idir
POST http://localhost:3000/assign-critter-to-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "animalId": [1482, 1449],
  "start": "2020-12-01",
  "end": "2021-12-01"
}

### should succeed with my idir
GET http://localhost:3000/users?idir={{idir}}

### should throw with idirtest2 - not an admin
GET http://localhost:3000/users?idir={{idirtest2}}

