@my_idir = {{idir}}
# @critter_no_access = {{existing_critter}}
# @critter_with_access = {{critter_with_change_permission}}

# get role - should fail user with idir stuff DNE
http://localhost:3000/get-user-role?idir=stuff

### should return administrator
http://localhost:3000/get-user-role?idir={{idir}}

### fail - unauthorized idir 
POST http://localhost:3000/add-user?idir=xyz HTTP/1.1
content-type: application/json

{
  "user": {
    "email": "someguy@qt.com",
    "domain": "idir"
  },
  "role": "administrator"
}

### fail - missing username
POST http://localhost:3000/add-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user": {
    "email": "someguy@qt.com",
    "domain": "idir"
  },
  "role": "administrator"
}
### fail - missing domain
POST http://localhost:3000/add-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user": {
    "username": "test1",
    "email": "someguy@qt.com"
  },
  "role": "administrator"
}

### fail - invalid role type
POST http://localhost:3000/add-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user": {
    "email": "someguy@qt.com",
    "username": "test001",
    "domain": "idir"
  },
  "role": "administrat"
}
### fail - username exists
POST http://localhost:3000/add-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user": {
    "email": "someguy@qt.com",
    "username": "{{idir}}",
    "domain": "idir"
  },
  "role": "administrator"
}

### success
POST http://localhost:3000/add-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user": {
    "username": "test1",
    "domain": "bceid",
    "email": "someguy@qt.com",
    "bceid": "test1"
  },
  "role": "observer"
}

### update existing user
POST http://localhost:3000/add-user?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "user": {
    "id": 1,
    "username": "{{idir}}",
    "email": "newemail@test.net",
    "domain": "idir"
  },
  "role": "observer"
}

### should succeed
# POST http://localhost:3000/assign-critter-to-user?idir={{idir}} HTTP/1.1
# content-type: application/json

# [{
#   "userId": "1",
#   "access": [{
#     "critter_id": "{{critter_no_access}}",
#     "permission_type": "change"
#   }]
# }]

### should succeed with my idir
GET http://localhost:3000/get-users?idir={{idir}}

# animal access permissions

### should succeed
GET http://localhost:3000/get-critter-access/{{idir}}?idir={{idir}}&keys=animal_id&term=68

### should fail
GET http://localhost:3000/get-critter-access/sdf?idir={{idir}}

### Get user with role info
GET http://localhost:3000/get-user?idir={{idir}}

### Get invalid user
GET http://localhost:3000/get-user?idir={{idirDNE}}

### Get alerts
GET http://localhost:3000/get-user-alerts?idir={{idir}}

### get critter groups udfs for idir user
GET http://localhost:3000/get-udf?idir={{idir}}&type=critter_group
### get collective unit udfs for idir user
GET http://localhost:3000/get-udf?idir={{idir}}&type=collective_unit

### get collective unit udfs for bceid user
GET http://localhost:3000/get-udf?bceid=kmb_bctw_editor3&type=collective_unit

### get critter group udfs for bceid user
GET http://localhost:3000/get-udf?bceid=kmb_bctw_editor3&type=critter_group

### add a udf
POST http://localhost:3000/add-udf?idir={{idir}} HTTP/1.1
content-type: application/json

{
  "type": "crittter_group",
  "key": "tg3",
  "value": [
    "2dcfd39b-c077-4cbd-97f0-528e9359c4c6",
    "8f640736-ccf3-4cdd-96c0-f63f2062c4ce",
    "20c28d11-9a94-4358-a9e6-eeed9ed17135"
  ]
}

### delete individual - fail (no permission)
DELETE http://localhost:3000/user/19?idir=dne HTTP/1.1

### delete individual - fail
DELETE http://localhost:3000/user/1900?idir={{idir}} HTTP/1.1

### delete individual - success
DELETE http://localhost:3000/user/19?idir={{idir}} HTTP/1.1