### get multiple critter history data 
POST http://localhost:3000/export?idir={{idir}}
content-type: application/json

{
"type": "animal",
"ids": [
"{{existing_critter}}",
"{{existing_critter2}}"
]
}


### get collar history data
POST http://localhost:3000/export?idir={{idir}}
content-type: application/json

{
  "type": "collar",
  "ids": [ "{{collar_attached_to_critter1}}" ]
}

### get 2 collar history data
POST http://localhost:3000/export?idir={{idir}}
content-type: application/json

{ 
  "type": "collar",
  "ids": [ "{{collar_attached_to_critter1}}", "{{existing_critter2}}" ]
 }

### get movement history
POST http://localhost:3000/export?idir={{idir}}
content-type: application/json

{ 
  "type": "movement",
  "ids": [ "{{existing_critter}}" ]
 }

### get movement history x2
POST http://localhost:3000/export?idir={{idir}} HTTP/1.1
content-type: application/json

{ 
  "type": "movement",
  "ids": [ "{{existing_critter}}", "{{existing_critter2}}" ]
 }