name: Test Suite

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bctw-api
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: bctw-api/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
